on:
  workflow_dispatch:
  schedule:
    - cron: '23 2 * * *'

name: Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Scala Steward
    steps:
      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-app-id: ${{ secrets.APP_ID }}
          github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
