on:
  workflow_dispatch:
  # schedule: # TODO reenable the schedule
  #   - cron: '23 2 * * *'

name: Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Scala Steward
    steps:
      # TODO scala-steward-action does not depend on the checkout action without it bun install is impossible
      # even if we add the checkout action, the scala-steward-action will checkout the repository again
      # and ignore the previous checkout action and the installed dependencies
      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-app-auth-only: true
          github-app-id: ${{ secrets.APP_ID }}
          github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
